### ISSUE TITLE
Error when running "yarn run prod"

### ISSUE THREAD

**Issue by lbausch** [Braunson/laravel-coreui-vue#1]
```
$ yarn run prod
yarn run v0.21.3
$ npm run production 

> @ production /tmp/laravel-coreui-vue
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                            

 ERROR  Failed to compile with 1 errors                                                       12:07:07 AM

 error  

/js/app.js from UglifyJs
Unexpected token: operator (>) [./~/vue-strap/src/utils/utils.js:4,0][/js/app.js:117308,16]
```

**Comment by Braunson** [comment]
It seems [UglifyJS2 doesn't support ES6 properly](https://github.com/mishoo/UglifyJS2/issues/448). So our options are...

**1. Disable Uglify for now in `webpack.mix.js`:** -- this apparently works but didn't for me.

--- 

**2. Installing the [Harmony Support UglifyJS2 branch](https://github.com/mishoo/UglifyJS2/issues/448)** by adding this line to your `packages.json` then running `rm -rf node_modules && npm install` and then `yarn run prod`.

```json
"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony"
```

Or you can add it using yarn cli `yarn add --dev git+https://github.com/mishoo/UglifyJS2.git#harmony`

This harmony branch doesn't cover all ES6 features but is a quick for for now until webpack ejects Uglify from it's core or the author's of Uglify push an update to support ES6 in it's entirety. **I've updated the code to make use of this harmony branch**.

---

Sidenote: I did see another _manual_ workaround [here](https://github.com/wffranco/vue-strap/issues/74#issuecomment-286520518)  but it's manually running in es2015 mode for the one file causing the issue `vue-strap/src/utils/utils.js` which isn't ideal anyway.

--- 

There's an ongoing issue page in the `webpack` repo [here](https://github.com/webpack/webpack/issues/2545) if your interested in more.

**Comment by lbausch** [comment]
Thank you for your detailed explanation but I cloned fresh instance of this repository and the error still appears. :/

**Comment by guenam** [comment]
I finally succeeded this way:
- delete node_modules
- delete in package.json the line for uglify
- yarn install
- yarn add --dev git+https://github.com/mishoo/UglifyJS2.git#harmony

A big thank you, @Braunson !

**Comment by Braunson** [comment]
@guenam Thank you for that solution, I'll give it a quick test and push an update to the repo soon!
